"""Provides access to secrets stored in a .env file."""
import os as _os
from pathlib import Path as _Path
from dotenv import load_dotenv as _load_dotenv

_load_dotenv()


def _get_setting(key: str) -> str:
    """Retrieve an environment variable."""
    return _os.environ.get(key)


DCA_TOJUST_NFU_DATABASE = _Path(_get_setting('DCA_TOJUST_NFU_DATABASE'))
DCA_TOJUST_TRANSACTION_DATABASE = _Path(_get_setting('DCA_TOJUST_TRANSACTION_DATABASE'))
DCA_TOJUST_AGMTS_DATABASE = _Path(_get_setting('DCA_TOJUST_AGMTS_DATABASE'))
DCA_TOJUST_ACTIVITY_DATABASE = _Path(_get_setting('DCA_TOJUST_ACTIVITY_DATABASE'))
DCA_TOJUST_CLOSURE_DATABASE = _Path(_get_setting('DCA_TOJUST_CLOSURE_DATABASE'))
DCA_TOJUST_QUERY_DATABASE = _get_setting('DCA_TOJUST_QUERY_DATABASE')

YU_TOJUST_NB_DATABASE = _Path(_get_setting('YU_TOJUST_NB_DATABASE'))
YU_TOJUST_QR_DATABASE = _get_setting('YU_TOJUST_QR_DATABASE')
YU_TOJUST_CLIENT_RECALL = _Path(_get_setting('YU_TOJUST_CLIENT_RECALL'))
YU_TOJUST_ADJUSTMENT = _Path(_get_setting('YU_TOJUST_ADJUSTMENT'))

AJJB_ACTIVITY_Input_Directory = _get_setting('AJJB_ACTIVITY_Input_Directory')
AJJB_CLOSURE_Input_Directory = _get_setting('AJJB_CLOSURE_Input_Directory')
AJJB_NFU_Input_Directory = _get_setting('AJJB_NFU_Input_Directory')
AJJB_PAYMENT_Input_Directory = _get_setting('AJJB_PAYMENT_Input_Directory')
AJJB_QUERY_Input_Directory = _get_setting('AJJB_QUERY_Input_Directory')

FROM_JUST_AJJB_PAY = _get_setting('PAY_AJJB_FROM_JUST')
FROM_JUST_AJJB_BU = _get_setting('BALANCE_UPDATE_FROM_JUST')
FROM_JUST_AJJB_CLOSURE = _get_setting('CLOSURE_FROM_JUST')
FROM_JUST_AJJB_PLACEMENT = _get_setting('PLACEMENT_FROM_JUST')

YU_NB_Input_Directory = _get_setting('YU_NB_Input_Directory')
YU_QR_Input_Directory = _get_setting('YU_QR_Input_Directory')
YU_CLIENT_RECALL_Input_Directory = _get_setting('YU_CLIENT_RECALL_Input_Directory')
YU_CLIENT_ADJUSTMENT_Input_Directory = _get_setting('YU_CLIENT_ADJUSTMENT_Input_Directory')
YU_CLIENT_QUERY_RESPONSE_Input_Directory = _get_setting('YU_CLIENT_QUERY_RESPONSE_Input_Directory')
First_LOCATE_Closure_Input_Directory = _get_setting('1ST_LOCATE_Closure_Input_Directory')
First_LOCATE_NFU_Input_Directory = _get_setting('1ST_LOCATE_NFU_Input_Directory')
First_LOCATE_Transaction_Input_Directory = _get_setting('1ST_LOCATE_Transaction_Input_Directory')
FIRST_LOCATE_PAY_DIRECTORY = _get_setting('1ST_LOCATE_PAY_Directory')
FIRST_LOCATE_BILL_DIRECTORY = _get_setting('1ST_LOCATE_BILL_Directory')
FIRST_LOCATE_RECALL_DIRECTORY = _get_setting('1st_LOCATE_RECALL_DIRECTORY')
FIRST_LOCATE_Activity_Directory = _get_setting('1ST_LOCATE_Activity_Directory')
FIRST_LOCATE_AGMTS_Directory = _get_setting('1ST_LOCATE_AGMTS_Directory')
FIRST_LOCATE_CLOSURE_Directory = _get_setting('1st_LOCATE_Closure_Directory')
FIRST_LOCATE_Query_Directory = _get_setting('1st_LOCATE_Query_Directory')
FIRST_LOCATE_QueryRESPONSE_Directory = _get_setting('1st_LOCATE_QUERYRESPONSE_DIRECTORY')
YU_NFU_DIRECTORY = _get_setting('YU_NFU_DIRECTORY')
YU_TRANSACTION_DIRECTORY = _get_setting('YU_TRANSACTION_DIRECTORY')
TRANSACTION_FROM_JUST_TO_YU = _get_setting('TRANSACTION_FROM_JUST_TO_YU')
YU_QUERY_DIRECTORY = _get_setting('YU_QUERY_DIRECTORY')
YU_CLOSURE_DIRECTORY = _get_setting('YU_CLOSURE_DIRECTORY')
IMPORT_REPORTS = _get_setting('IMPORT_REPORTS')

DAILY_REPORTS = _get_setting('DAILY_REPORTS')
SEND_GRID_API_KEY = _get_setting('SEND_GRID_API_KEY')

FIRST_LOCATE_ASSIGNMENT_DIRECTORY = _get_setting('1ST_LOCATE_ASSIGNMENT_DIRECTORY')
CASTLEWATER_ASSIGNMENT_DIRECTORY = _get_setting('CASTLEWATER_ASSIGNMENT_DIRECTORY')
ASSIGNMENT_FROM_JUST_TO_FIRST_LOCATE = _get_setting('ASSIGNMENT_FROM_JUST_TO_FIRST_LOCATE')
PAY_FROM_JUST_TO_FIRST_LOCATE = _get_setting('PAY_FROM_JUST_TO_FIRST_LOCATE')
BILL_FROM_JUST_TO_FIRST_LOCATE = _get_setting('BILL_FROM_JUST_TO_FIRST_LOCATE')
QR_FROM_JUST_TO_FIRST_LOCATE = _get_setting('QR_FROM_JUST_TO_FIRST_LOCATE')
RECALL_FROM_JUST_TO_FIRST_LOCATE = _get_setting('RECALL_FROM_JUST_TO_FIRST_LOCATE')
NFU_FROM_JUST_TO_YU = _get_setting('NFU_FROM_JUST_TO_YU')
CLOSURE_FROM_JUST_TO_YU = _get_setting('CLOSURE_FROM_JUST_TO_YU')
QUERY_FROM_JUST_TO_YU = _get_setting('QUERY_FROM_JUST_TO_YU')



#Incoming Batch Files - To be run in call_batch_files.py
FIRST_LOCATE_ACTIVITY_INCOMING_BATCH_FILE = _get_setting('FIRST_LOCATE_ACTIVITY_INCOMING_BATCH_FILE')
FIRST_LOCATE_AGMTS_INCOMING_BATCH_FILE = _get_setting('FIRST_LOCATE_AGMTS_INCOMING_BATCH_FILE')
FIRST_LOCATE_CLOSURE_INCOMING_BATCH_FILE = _get_setting('FIRST_LOCATE_CLOSURE_INCOMING_BATCH_FILE')
FIRST_LOCATE_NFU_INCOMING_BATCH_FILE = _get_setting('FIRST_LOCATE_NFU_INCOMING_BATCH_FILE')
FIRST_LOCATE_QUERY_INCOMING_BATCH_FILE = _get_setting('FIRST_LOCATE_QUERY_INCOMING_BATCH_FILE')
FIRST_LOCATE_TRANSACTION_INCOMING_BATCH_FILE = _get_setting('FIRST_LOCATE_TRANSACTION_INCOMING_BATCH_FILE')

YU_ADJUSTMENT_INCOMING_BATCH_FILE = _get_setting('YU_ADJUSTMENT_INCOMING_BATCH_FILE')
YU_NB_INCOMING_BATCH_FILE = _get_setting('YU_NB_INCOMING_BATCH_FILE')
YU_QR_INCOMING_BATCH_FILE = _get_setting('YU_QR_INCOMING_BATCH_FILE')
YU_CLOSURE_INCOMING_BATCH_FILE = _get_setting('YU_CLOSURE_INCOMING_BATCH_FILE')


TO_JUST_AJJB_ACTIVITY = _get_setting('TO_JUST_AJJB_ACTIVITY')
TO_JUST_AJJB_CLOSURE = _get_setting('TO_JUST_AJJB_CLOSURE')
TO_JUST_AJJB_NFU = _get_setting('TO_JUST_AJJB_NFU')
TO_JUST_AJJB_PAYMENT = _get_setting('TO_JUST_AJJB_PAYMENT')
TO_JUST_AJJB_QUERIES = _get_setting('TO_JUST_AJJB_QUERIES')

TO_CREDIT_SAFE_BATCH_FILE = _get_setting('TO_CREDIT_SAFE_BATCH_FILE')
TO_TRANSUNION_BATCH_FILE = _get_setting('TO_TRANSUNION_BATCH_FILE')


CASES_FOR_LITIGATION = _get_setting('CASES_FOR_LITIGATION')

TO_CREDIT_SAFE = _get_setting('TO_CREDIT_SAFE')
TO_TRANSUNION = _get_setting('TO_TRANSUNION')


FROM_CREDIT_SAFE = _get_setting('FROM_CREDIT_SAFE')
FROM_TRANSUNION = _get_setting('FROM_TRANSUNION')
FROM_CREDITSAFE_BATCHFILE = _get_setting('FROM_CREDITSAFE_FILE')
FROM_Transunion_BATCHFILE = _get_setting('FROM_Transunion_FILE')


FROM_JUST_AJJB_TRANSACTION_BATCH = _get_setting('FROM_JUST_AJJB_TRANSACTION')
FROM_JUST_AJJB_BALANCE_UPDATE_BATCH = _get_setting('FROM_JUST_AJJB_BALANCE_UPDATE')
FROM_JUST_AJJB_CLOSURE_BATCH = _get_setting('FROM_JUST_AJJB_CLOSURE')
FROM_JUST_AJJB_PLACEMENT_BATCH = _get_setting('FROM_JUST_AJJB_PLACEMENT')

